---                                                                             
- hosts: all                                                                 
  gather_facts: no                                                              
                                                                                
  tasks:                                                                        
  - include: roles/reboot/tasks/main.yml                                      
