- name: check if reboot-required file is present
  stat: path=/var/run/reboot-required
  register: reboot_required

- name: Restart server
  become: yes
  shell: sleep 2 && /sbin/shutdown -r now "Ansible system package upgraded"
  async: 1
  poll: 0
  when: reboot_required.stat.exists == True

- name: waiting 60 secs for server to come back
  local_action: wait_for host=127.0.0.1 port=2222 delay=20 connect_timeout=200
  become: false
  delegate_to:  127.0.0.1
  when: reboot_required.stat.exists == True
